import type { Product } from './product';

function productImage(fileName: string): string {
  return `${import.meta.env.BASE_URL}products/${fileName}`;
}

export const products: Product[] = [
  {
    id: 'p1',
    slug: 'pulse-headphone-pro',
    name: 'Fone de Ouvido Bluetooth Pulse ANC 700',
    category: 'Áudio',
    description: 'Fone circum-aural com cancelamento ativo de ruído e conexão para dois dispositivos.',
    details: ['Cancelamento de ruído híbrido', 'Bateria de até 38 horas', 'Bluetooth multiponto'],
    priceCents: 89990,
    previousPriceCents: 109990,
    stock: 18,
    rating: 4.9,
    reviews: 286,
    image: productImage('headphone.png'),
    badge: 'Mais vendido',
  },
  {
    id: 'p2',
    slug: 'flow-keyboard-75',
    name: 'Teclado Mecânico Flow 75 ABNT2',
    category: 'Periféricos',
    description: 'Teclado compacto com layout ABNT2, conexão sem fio e switches substituíveis.',
    details: ['Layout ABNT2', 'Switches hot-swap', 'Bluetooth, USB e receptor 2,4 GHz'],
    priceCents: 64990,
    stock: 22,
    rating: 4.8,
    reviews: 174,
    image: productImage('keyboard.png'),
    badge: 'Lançamento',
  },
  {
    id: 'p3',
    slug: 'arc-mouse',
    name: 'Mouse Sem Fio Arc Precision M2',
    category: 'Periféricos',
    description: 'Mouse ergonômico com sensor ajustável, sete botões e recarga por USB-C.',
    details: ['Sensor de até 26.000 DPI', 'Sete botões programáveis', 'Bluetooth e receptor 2,4 GHz'],
    priceCents: 38990,
    previousPriceCents: 42990,
    stock: 31,
    rating: 4.7,
    reviews: 322,
    image: productImage('mouse.png'),
  },
  {
    id: 'p4',
    slug: 'horizon-monitor-27',
    name: 'Monitor Horizon QHD 27 USB-C',
    category: 'Monitores',
    description: 'Monitor IPS de 27 polegadas com resolução QHD, 100 Hz e alimentação por USB-C.',
    details: ['Painel IPS QHD', 'Taxa de atualização de 100 Hz', 'USB-C com entrega de até 90 W'],
    priceCents: 249990,
    stock: 9,
    rating: 4.9,
    reviews: 91,
    image: productImage('monitor.png'),
    badge: 'Recomendado',
  },
  {
    id: 'p5',
    slug: 'orbit-smartwatch',
    name: 'Smartwatch Orbit Active 2',
    category: 'Mobilidade',
    description: 'Relógio inteligente com GPS, monitoramento de atividades e autonomia de até sete dias.',
    details: ['GPS integrado', 'Bateria de até sete dias', 'Resistência à água 5 ATM'],
    priceCents: 79990,
    stock: 16,
    rating: 4.6,
    reviews: 143,
    image: productImage('watch.png'),
  },
  {
    id: 'p6',
    slug: 'wave-speaker',
    name: 'Caixa de Som Wave Mini USB-C',
    category: 'Áudio',
    description: 'Caixa de som compacta para mesa com conexão USB-C e controle frontal de volume.',
    details: ['Áudio estéreo', 'Alimentação por USB-C', 'Controle físico de volume'],
    priceCents: 45990,
    stock: 25,
    rating: 4.7,
    reviews: 118,
    image: productImage('speaker.png'),
  },
  {
    id: 'p7',
    slug: 'focus-webcam-4k',
    name: 'Webcam Focus 4K com Tampa',
    category: 'Vídeo',
    description: 'Webcam 4K com enquadramento automático, microfones duplos e tampa física de privacidade.',
    details: ['Resolução 4K HDR', 'Enquadramento automático', 'Tampa física de privacidade'],
    priceCents: 72990,
    stock: 12,
    rating: 4.8,
    reviews: 87,
    image: productImage('webcam.png'),
  },
  {
    id: 'p8',
    slug: 'rise-laptop-stand',
    name: 'Suporte para Notebook Rise Alumínio',
    category: 'Escritório',
    description: 'Suporte dobrável em alumínio com seis níveis de altura para notebooks de até 17 polegadas.',
    details: ['Seis níveis de altura', 'Estrutura dobrável', 'Compatível com notebooks de até 17 polegadas'],
    priceCents: 27990,
    stock: 44,
    rating: 4.7,
    reviews: 205,
    image: productImage('stand.png'),
  },
  {
    id: 'p9',
    slug: 'link-hub-9',
    name: 'Hub USB-C Link 9 em 1',
    category: 'Conectividade',
    description: 'Hub com HDMI, rede Gigabit, leitores de cartão, portas USB e carregamento pass-through.',
    details: ['HDMI com saída 4K', 'Ethernet Gigabit', 'Power Delivery de até 100 W'],
    priceCents: 41990,
    stock: 30,
    rating: 4.6,
    reviews: 164,
    image: productImage('hub.png'),
  },
  {
    id: 'p10',
    slug: 'beam-desk-light',
    name: 'Luminária de Mesa Beam LED',
    category: 'Escritório',
    description: 'Luminária articulada com ajuste de intensidade e temperatura de cor.',
    details: ['Intensidade regulável', 'Três temperaturas de cor', 'Alimentação por USB-C'],
    priceCents: 34990,
    stock: 20,
    rating: 4.8,
    reviews: 73,
    image: productImage('lamp.png'),
  },
  {
    id: 'p11',
    slug: 'move-tech-backpack',
    name: 'Mochila Executiva Move 16',
    category: 'Mobilidade',
    description: 'Mochila para notebook de até 16 polegadas com divisórias internas e tecido resistente à água.',
    details: ['Compartimento para notebook de 16 polegadas', 'Tecido resistente à água', 'Organização interna modular'],
    priceCents: 51990,
    stock: 27,
    rating: 4.7,
    reviews: 136,
    image: productImage('backpack.png'),
  },
  {
    id: 'p12',
    slug: 'core-office-chair',
    name: 'Cadeira Ergonômica Core Mesh',
    category: 'Escritório',
    description: 'Cadeira de escritório com encosto em tela, apoio lombar e braços ajustáveis.',
    details: ['Apoio lombar regulável', 'Braços com ajuste 3D', 'Encosto em tela respirável'],
    priceCents: 189990,
    stock: 7,
    rating: 4.9,
    reviews: 68,
    image: productImage('chair.png'),
    badge: 'Ergonomia',
  },
];

export const categories = ['Todos', ...Array.from(new Set(products.map((product) => product.category)))];

export function productBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}
